apiVersion: v1
kind: Pod
metadata:
        name: myapp-pod
        labels:
                app: myapp
                type:  front-end
spec:
        containers:
                - name: nginx-container
                  image: nginx
        nodeName: gke-cluster-1-pool-1-1105dbdb-tqt5  
        tolerations: 
                - key: "app"
                  operator: "Equal"
                  value: "myapp"
                  effect: "NoSchedule"
              
